name: Versioning

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Release Please Action
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          pull-request-title-pattern: 'chore: Release ${version}'
